# Service for Redis
apiVersion: v1
kind: Service
metadata:
  name: redis-public-svc
  namespace: books-app
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379