# Service for RabbitMQ
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: books-app
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672 # For RabbitMQ management UI
      targetPort: 15672
  # clusterIP: None # Headless service for StatefulSet
