# Service for Auth Service (HTTP & gRPC)
apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
  namespace: books-app
spec:
  selector:
    app: auth-service # Matches the Deployment's labels
  ports:
    - name: http-api
      protocol: TCP
      port: 80 # Internal service port for HTTP
      targetPort: 8000 # Container's HTTP port
    - name: grpc-api
      protocol: TCP
      port: 50051 # Internal service port for gRPC
      targetPort: 50051 # Container's gRPC port
  type: ClusterIP
