# Service for Books Service PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgresql-books-svc
  namespace: books-app
spec:
  selector:
    app: postgres-books
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
